name: Build and Test Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - win_test_wifi
          - win_test_uart
          - win_test_clock
          - win_test_light
          - win_test_timestamp
          - win_test_buttons
          - win_test_adxl345
          - win_test_buzzer
          - win_test_hcsr04
          - win_test_pir
          - win_test_pc_comm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Run PlatformIO tests (${{ matrix.env }})
        run: pio test -e ${{ matrix.env }}
