name: Build and Test Firmware

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env-name:
          - target_test
          - win_test
          - win_test_wifi
          - win_test_pc_comm
          - win_test_light

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Run PlatformIO for ${{ matrix.env-name }}
        # For your AVR test env this is a build (no upload).
        # For native ones this invokes the Unity tests.
        run: |
          if [[ "${{ matrix.env-name }}" == "target_test" ]]; then
            pio run -e target_test
          else
            pio test -e ${{ matrix.env-name }}
          fi
